### PR TITLE
Allow proceeding zeros in factional seconds

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Allow proceeding zeros in factional seconds.

This addresses the issue identified in usnistgov/liboscal-java#141 and https://github.com/usnistgov/OSCAL/issues/1774.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [x] Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

### CODE REVIEW

**Review by aj-stein-nist — DISMISSED** [review]
I am good with the change, I would recommend adding the example `2019-09-28T23:00:00.0Z` or one with more trailing zeros so we can copy-paste the [examples in the datatypes page so I can use things like regex101.com](https://regex101.com/r/TiJPS9/1) to make testing quicker.

We also want to optionally consider change the 60 second examples because those don't validate (such at `60` in `2019-12-31T23:59:60Z` because of how seconds work), but that is minor. Otherwise, this looks good!

**Review by nikitawootten-nist — APPROVED** [review]
@wendellpiez and I generated the OSCAL schemas and have confirmed that this fixes usnistgov/OSCAL#1774. Looks good to us!

**Review by wendellpiez — APPROVED** [review]
We reviewed and validated the regex (and learned many things about the containers/distro while doing so) thanks for the work

**Review by nikitawootten-nist — CHANGES_REQUESTED** [review]
Could you add an example to the following schema validation test: https://github.com/usnistgov/metaschema/blob/main/test-suite/schema-generation/datatypes/datatypes-datetime_test_valid_PASS.json

**Pull request merged**
