### PR TITLE
Change XSLT JSON Schema gen to allow $schema directive

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

Add `$schema`  directive to the XSLT implementation, closing usnistgov/metaschema#383.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you included examples of how to use your new feature(s)?
- ~Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
It seems I borked this earlier and just pushed the actual stylesheet change. @wendellpiez, I am looking into how to not inject that schema into nested schemas when using the `import` directive and having composite schemas for modules that are sub-modules (like oscal_complete_schema.json should have a `$schema` but not the embedded SSP schema within it, but when self-contained in the oscal_ssp_schema.json it can have it), but I will soon be ready for tests and integration.

**Review by wendellpiez — COMMENTED** [review]
Forgive me for not looking it up, but is the property optional if not said to be required? Let's see that testing includes validating some JSON that does not have this property set.

Q: what happens if the property is set but defective?

**Comment by aj-stein-nist** [comment]
> Forgive me for not looking it up, but is the property optional if not said to be required? Let's see that testing includes validating some JSON that does not have this property set.

It is optional [per the spec](https://json-schema.org/understanding-json-schema/reference/schema.html):

> The $schema keyword is used to declare which dialect of JSON Schema the schema was written for. The value of the $schema keyword is also the identifier for a schema that can be used to verify that the schema is valid according to the dialect $schema identifies. A schema that describes another schema is called a “meta-schema”.
>
> $schema applies to the entire document and must be at the root level. It does not apply to externally referenced ($ref, $dynamicRef) documents. Those schemas need to declare their own $schema.


> Q: what happens if the property is set but defective?

Also totally agree with the testing, I just haven't set out the mechanics and I was holding off see if the other relevant JSON schema gen PR merged, and it has not yet. I will be adding tests to this PR and may need to reach out for help regarding the mechanics of that part I explained I had not solved yet. Not sure about the order yet, so maybe I go to tests alongside that exploration.
Also from the spec at the same link:

> If $schema is not used, an implementation might allow you to specify a value externally or it might make assumptions about which specification version should be used to evaluate the schema. It’s recommended that all JSON Schemas have a $schema keyword to communicate to readers and tooling which specification version is intended.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist and @wendellpiez, tests are updated. This is ready for review.

**Review by david-waltermire-nist — APPROVED** [review]
I ran the tests and manually reviewed them. They look good.
Thanks!

**Review by wendellpiez — CHANGES_REQUESTED** [review]
There are a bunch of XSpec artifacts here; should they be included?

Suggest adding those to .gitignore?

I like where this is going very much. 🥬 🥕

**Comment by aj-stein-nist** [comment]
> There are a bunch of XSpec artifacts here; should they be included? In general, an `xspec` directory, any HTML file reports etc. are ephemeral and can be excluded.
> 
> Suggest adding those to .gitignore?

Thanks for calling this out, I didn't even notice! I edited and cleaned up and force-pushed from https://github.com/usnistgov/metaschema/commit/1b4a99620aa5f4b5f348c2a4e599f5970c7e1a08 to https://github.com/usnistgov/metaschema/commit/ffd46653d76dbe0dc7a273510a5abe20d098f8e6 to not clutter up the commits and commit log with it, adding a `.gitignore` directive in one moment, @wendellpiez.

**Comment by aj-stein-nist** [comment]
And .gitignore updated in https://github.com/usnistgov/metaschema/pull/384/commits/3574b362381a1b283bc5d49d79d0079e846d8387, @wendellpiez. I would love a re-review.

**Review by david-waltermire-nist — APPROVED** [review]
Thanks for removing and ignoring the generated files.

**Pull request merged**
