### PR TITLE
Migrate from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This PR will add one or more GitHub Action workflows, and the jobs that comprise them, to replace and deprecate the use of CircleCI for this repository. This PR closes usnistgov/metaschema#200 and closes usnistgov/metaschema#192.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you included examples of how to use your new feature(s)?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
Also, @david-waltermire-nist, it seems `master` and `develop` are aligned with each other for now, but where do you want this PR to target? I know GHA gets very weird with rolling out CI/CD updates until they are merged into master (unless configured otherwise), so I will point it to there unless you ask for otherwise. Let me know!

**Comment by aj-stein-nist** [comment]
Making some more progress, but I am not sure why hugo is missing some pieces of the site. Will have to troubleshoot tomorrow and potentially pair with the rest of the dev team.

image

**Comment by aj-stein-nist** [comment]
Meeting with Dave later today to cover some of this stuff and get it ready for formal review. Haven't figured out the disparties with the website generation steps, but if it is submodule-based, I am sure I will hear about it. 😝

**Comment by aj-stein-nist** [comment]
Making some more progress, but [as of current builds](https://github.com/aj-stein-nist/metaschema/runs/6024886547?check_suite_focus=true) it seems whatever gets built by `hugo` is not detected as changed by `git` after the build, not sure why.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist ok I finished touch-ups after today's pairing session. It is ready for final review.

**Comment by aj-stein-nist** [comment]
OK, @david-waltermire-nist, this should be ready ready this time. One last bit we discussed about relocating the `.lycheeignore` from the repo root directory to the newly created `./build/config` dir, to match OSCAL, and place alongside the `./build/config/.markdown-link-check` configuration is now added and I squashed the commit. Once this is merged, I will implement elsewhere as agreed.

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
