### PR TITLE
Add `collapsible` to `GlobalFieldDefinitionType` type in XSD

### LINKED ISSUE #774: `GlobalFieldDefinitionType` missing definition for `collapsible` causing failure in `test-suite` sample
# Describe the bug

The `metaschema.xsd` file defines a number of types for Metaschema.

The `GlobalFieldDefinitionType` has the following definition:

```xml
  <xs:complexType name="GlobalFieldDefinitionType">
    <xs:annotation>
      <xs:documentation>In JSON, an object with a nominal string value (potentially with internal
        inline - not fully structured - markup). In XML, an element with string or markup
        content. Defined globally, a field can be assigned to appear in the <code>model</code> of any assembly by <code>field</code> reference.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="DefinitionMetadataGroup"/>
      <xs:group ref="UseNamingGroup"/>
      <xs:element name="json-key" type="JsonKeyType" minOccurs="0"/>
      <xs:group ref="JsonValueKeyChoiceGroup"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="flag" type="FlagReferenceType"/>
        <xs:element name="define-flag" type="InlineFlagDefinitionType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:element name="constraint" type="DefineFieldConstraintsType" minOccurs="0"/>
      <xs:element name="remarks" type="RemarksType" minOccurs="0"/>
      <xs:element name="example" type="ExampleType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="FieldValueAttributeGroup"/>
    <xs:attributeGroup ref="DefinitionNamingGroup"/>
    <xs:attribute name="scope" type="ScopeType" default="global"/>
    <xs:attributeGroup ref="DeprecationAttributeGroup"/>
  </xs:complexType>
```

Notice there is no definition of `collapsible`.

However, the test suite contains the following file:
* `test-suite/schema-generation/collapsible/collapsible-no-op_metaschema.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../../toolchains/xslt-M4/validate/metaschema-composition-check.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!-- OSCAL CATALOG METASCHEMA -->
<!-- validate with XSD and Schematron (linked) -->
<METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
   <schema-name>Metaschema Unit Test: collapsible-no-op</schema-name>
   <schema-version>1.0-milestone1</schema-version>
   <short-name>metaschema-collapsible-no-op</short-name>
   <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/collapsible-no-op</namespace>
   <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/collapsible-no-op</json-base-uri>
   <define-assembly name="parent">
      <formal-name>parent</formal-name>
      <description>parent assembly</description>
      <root-name>parent</root-name>
      <model>
         <field ref="prop" min-occurs="1" max-occurs="unbounded">
            <group-as name="props" in-json="SINGLETON_OR_ARRAY"/>
         </field>
      </model>
   </define-assembly>
   <define-field name="prop" as-type="string" collapsible="yes">
      <formal-name>prop</formal-name>
      <description>prop field</description>
   </define-field>
</METASCHEMA>
```

Notice that this line:
```
   <define-field name="prop" as-type="string" collapsible="yes">
```

Clearly indicates that `define-field` supports the `collapsible` attribute. `define-field` is exactly of the type `GlobalFieldDefinitionType`, because it directly belongs to `<METASCHEMA>`:

```xml
  <xs:element name="METASCHEMA">
    <xs:annotation>
      <xs:documentation>Root element of a Metaschema definition. Defines a family of data
        structures representing a model.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <!-- -->
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="define-assembly" type="GlobalAssemblyDefinitionType"/>
          <xs:element name="define-field" type="GlobalFieldDefinitionType"/>
          <xs:element name="define-flag" type="GlobalFlagDefinitionType"/>
        </xs:choice>
      </xs:sequence>
```

# Expected behavior (i.e. solution)

The solution is to update the definition of `GlobalFieldDefinitionType` to support `collapsible`.

# Other Comments

I will submit a PR that addresses this issue.

### PR DESCRIPTION
**Pull request by ronaldtse**
# Committer Notes

Fixes #774

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@wendellpiez @david-waltermire FYI.

**Comment by david-waltermire** [comment]
This was intentionally removed long ago and support has been removed in the Java and XSLT implementations. This feature is not used in OSCAL.

**Comment by wendellpiez** [comment]
:+1: thanks for confirming this, @david-waltermire.

**Review by iMichaela — COMMENTED** [review]
Feature not desired (see comments above).

**Pull request closed without merging**
