### PR TITLE
Redefined lexical constraint on 'token' datatype 

### PR DESCRIPTION
**Pull request by wendellpiez**
Addressing #181

# Committer Notes

In this PR, references to upper-Unicode characters that break at least one processor in the XSD that break at least one processor (in the `token` datatype definition) have been removed.

*This is a change only in the XSD syntax not in any definitions.* The datatype (mirroring NCName) *is not actually being relaxed here*, since the exclusion we are removing tests out as inoperative. The offending characters (starting with \u10000) are not in the sets from which they are being excluded (XML name character `\c` and initial name character `\i`). (We should have detected this discrepancy earlier, but didn't.)

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

### CODE REVIEW

**Review by aj-stein-nist — DISMISSED** [review]
Hey @wendellpiez, @david-waltermire-nist asked I review this pull request. I tested it on my workstation and ran the pipeline locally with the code as configured in usnistgov/OSCAL#1161 (the GitHub Actions do not run the metaschema-artifacts job since it is just a submodule update). Given that we tested these exact regexes to not fail in the C# harness here in [Issue1127Example repo Schema12 test](https://github.com/aj-stein-nist/Issue1127Example/blob/a8d9c3867177a34b5d58d66cc2a4c6ff335994a9/Fixtures/SchemaPattern12.xsd#L9-L18), I removed draft status from this PR and definitely approve moving it forward. 🚢

**Comment by wendellpiez** [comment]
NB: the scope of this PR has changed. It now includes work addressing https://github.com/usnistgov/OSCAL/issues/1186, which supersedes the datatype adjustments included here.

**Comment by wendellpiez** [comment]
@aj-stein-nist the adjusted schema generators here support the new improved datatype definitions while also being backward compatible - feel free to give them a go (JSON Schema and XSD generators should update).

**Comment by wendellpiez** [comment]
Code in this commit now produces decent-looking XSD and JSON Schemas from the pipeline, with updated datatypes.

We should address datatype alignment again after new Metaschema schemas and infrastructure is deployed. We can then remove use of old datatypes in the metaschema sources, and tighten all this back.

However, this is ready for updating data type support for 1.0.3 (assuming it integrates and passes downstream checks).

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
